### ISSUE TITLE
dashboard.component.scss

### ISSUE THREAD

**Issue by psalm119** [Angular-istic/sidenav#1]
Hello, can you please post the SCSS for the dashboard component that's shown in the video "Adding Responsive Toolbar | Part 3 | Responsive Sidenav"? It can be seen here...  @[50:30](https://youtu.be/wRXdy9Vag90&t=3030s)

Actually, I was able to piece the code together somewhat by freeze-framing the video but there's a chuck of code, lines 54-76, that are not able to be shown in the video since it moves too fast :).

Kind regards.
Ben Williams

![dashboard scss-2022-09-08_14-45-03](https://user-images.githubusercontent.com/8977479/189212242-a8d6aad9-ec9f-40cf-9a70-0ed93517b0f4.gif)

**Comment by Angular-istic** [comment]
h2 {
    color: #495057;
}

.row {
    display: flex;
    flex-direction: row;

    .col-left {
        width: 65%;
    }

    .col {
        margin: 20px 0 0 20px;
        width: 35%;
    }
}

.row-md {
    display: flex;
    flex-direction: column;

    .col-left {
        width: 100%;
    }
}

.task-col {
    .task {
        background: #fff;
        padding: 20px;
        border-radius: 8px;
        margin-bottom: 15px;
        display: flex;
        color: #495057;
        box-shadow: 0 .25rem .5rem #e6edef;

        .edit {
            margin: auto 0 auto auto;
            width: 20px;
            height: 20px;
            cursor: pointer;
        }

        .bar {
            width: 5px;
            height: 45px;
            border-radius: 15px;
            margin-right: 15px;

            &.completed {
                background: rgb(238, 139, 9);
            }

            &.active {
                background: rgb(9, 127, 238);
            }

            &.new {
                background: rgb(130, 189, 243);
            }
        }

        .details {
            display: flex;
            flex-direction: column;
            justify-content: center;

            p {
                color: #74788d;
                font-size: 14px;
                margin-top: 2px;
            }
        }
    }

    button {
        cursor: pointer;
        border: none;
        outline: 0;
        color: #fff;
        background-color: #556ee6;
        padding: 12px 17px;
        border-radius: 5px;
        width: 100%;

        margin-right: 10px;
    }
}

.welcome-card {
    border-radius: 0.25rem;
    max-width: 740px;

    .welcome-head-container {
        background-color: #556ee640;
        color: #556ee6;
        font-size: 16px;
        display: flex;
        flex-wrap: wrap;
        border-top-right-radius: 5px;
        border-top-left-radius: 5px;
    
        .col-left {
            flex: 0 0 auto;
            width: 58.33333333%;

            p {
                font-size: 14px;
                margin-top: 7px;
                font-weight: normal;
            }
        }
    
        .col-right {
            flex: 0 0 auto;
            width: 41.66666667%;
    
            img {
                width: 65%;
                height: auto;
            }
        }
    }
    
    .welcome-body-container {
        display: flex;
        flex-wrap: wrap;
    
        .col-left {
            flex: 0 0 auto;
            width: 33.33333333%;
        
            .avatar {
                margin-top: -36px;
                margin-bottom: 1.5rem;
                height: 4.5rem;
                width: 4.5rem;
        
                img {
                    border-radius: 50%;
                    padding: 0.25rem;
                    background-color: #f8f8fb;
                    border: 1px solid #f6f6f6;
                    max-width: 100%;
                    height: auto;
                }
            }
        
            .name {
                font-size: 16px;
                font-weight: 500;
                margin-bottom: .5rem;
            }
        
            p {
                color: #74788d;
                font-size: 14px;
            }
        }
        
        .col-right {
            flex: 0 0 auto;
            width: 66.66666667%;

            .performance-container {

                .performance {
                    display: flex;
                    justify-content: space-between;
                    margin-bottom: 10px;
                    font-size: 14px;
                    font-weight: 400;
                    color: #74788d;
                }
                
                .progress {
                    display: flex;
                    height: 7px;
                    overflow: hidden;
                    font-size: .75rem;
                    background-color: #e9ecef;
                    border-radius: 0.25rem;
                    .progress-bar {
                        width: 80%;
                        background-color: rgb(50, 248, 60);
                    }
                }
            }

            .view-profile {
                margin-top: 1rem;

                button {
                    cursor: pointer;
                    border: none;
                    outline: 0;
                    color: #fff;
                    background-color: #556ee6;
                    padding: 12px 17px;
                    border-radius: 5px;

                    .fa-arrow-right {
                        margin-left: 10px;
                    }
                }
            }
        }
    }
}

**Comment by Angular-istic** [comment]
h2 {
    color: #495057;
}

.row {
    display: flex;
    flex-direction: row;

    .col-left {
        width: 65%;
    }

    .col {
        margin: 20px 0 0 20px;
        width: 35%;
    }
}

.row-md {
    display: flex;
    flex-direction: column;

    .col-left {
        width: 100%;
    }
}

.task-col {
    .task {
        background: #fff;
        padding: 20px;
        border-radius: 8px;
        margin-bottom: 15px;
        display: flex;
        color: #495057;
        box-shadow: 0 .25rem .5rem #e6edef;

        .edit {
            margin: auto 0 auto auto;
            width: 20px;
            height: 20px;
            cursor: pointer;
        }

        .bar {
            width: 5px;
            height: 45px;
            border-radius: 15px;
            margin-right: 15px;

            &.completed {
                background: rgb(238, 139, 9);
            }

            &.active {
                background: rgb(9, 127, 238);
            }

            &.new {
                background: rgb(130, 189, 243);
            }
        }

        .details {
            display: flex;
            flex-direction: column;
            justify-content: center;

            p {
                color: #74788d;
                font-size: 14px;
                margin-top: 2px;
            }
        }
    }

    button {
        cursor: pointer;
        border: none;
        outline: 0;
        color: #fff;
        background-color: #556ee6;
        padding: 12px 17px;
        border-radius: 5px;
        width: 100%;

        margin-right: 10px;
    }
}

.welcome-card {
    border-radius: 0.25rem;
    max-width: 740px;

    .welcome-head-container {
        background-color: #556ee640;
        color: #556ee6;
        font-size: 16px;
        display: flex;
        flex-wrap: wrap;
        border-top-right-radius: 5px;
        border-top-left-radius: 5px;
    
        .col-left {
            flex: 0 0 auto;
            width: 58.33333333%;

            p {
                font-size: 14px;
                margin-top: 7px;
                font-weight: normal;
            }
        }
    
        .col-right {
            flex: 0 0 auto;
            width: 41.66666667%;
    
            img {
                width: 65%;
                height: auto;
            }
        }
    }
    
    .welcome-body-container {
        display: flex;
        flex-wrap: wrap;
    
        .col-left {
            flex: 0 0 auto;
            width: 33.33333333%;
        
            .avatar {
                margin-top: -36px;
                margin-bottom: 1.5rem;
                height: 4.5rem;
                width: 4.5rem;
        
                img {
                    border-radius: 50%;
                    padding: 0.25rem;
                    background-color: #f8f8fb;
                    border: 1px solid #f6f6f6;
                    max-width: 100%;
                    height: auto;
                }
            }
        
            .name {
                font-size: 16px;
                font-weight: 500;
                margin-bottom: .5rem;
            }
        
            p {
                color: #74788d;
                font-size: 14px;
            }
        }
        
        .col-right {
            flex: 0 0 auto;
            width: 66.66666667%;

            .performance-container {

                .performance {
                    display: flex;
                    justify-content: space-between;
                    margin-bottom: 10px;
                    font-size: 14px;
                    font-weight: 400;
                    color: #74788d;
                }
                
                .progress {
                    display: flex;
                    height: 7px;
                    overflow: hidden;
                    font-size: .75rem;
                    background-color: #e9ecef;
                    border-radius: 0.25rem;
                    .progress-bar {
                        width: 80%;
                        background-color: rgb(50, 248, 60);
                    }
                }
            }

            .view-profile {
                margin-top: 1rem;

                button {
                    cursor: pointer;
                    border: none;
                    outline: 0;
                    color: #fff;
                    background-color: #556ee6;
                    padding: 12px 17px;
                    border-radius: 5px;

                    .fa-arrow-right {
                        margin-left: 10px;
                    }
                }
            }
        }
    }
}

**Comment by psalm119** [comment]
Thank you.

**Comment by Akhilmanikandan47** [comment]
can you please post the code for dashboard html as well?

**Comment by gatchang-stephen** [comment]
> can you please post the code for dashboard html as well?
```
<h2>Dashboard</h2>

<div [ngClass]="getClass()">
  <div class="col-left">
    <div class="card welcome-card">
      <div class="card-head welcome-head-container">
        <div class="col-left">
          <div>Welcome Back !</div>
          <p>Angular Dashboard</p>
        </div>
        <div class="col-right">
          <img [src]="'https://placehold.co/600x400/000000/FFFFFF/png'" alt="" />
        </div>
      </div>
      <div class="card-body welcome-body-container">
        <div class="col-left">
          <div class="avatar">
            <img `[src]="'https://placehold.co/600x400/000000/FFFFFF/png'"` alt="profile picture" />
          </div>
          <div class="name">John Doe</div>
          <p>Web Developer</p>
        </div>
        <div class="col-right">
          <div class="performance-container">
            <div class="performance">
              <div>Performance</div>
              <div>80%</div>
            </div>
            <div class="progress">
              <div class="progress-bar"></div>
            </div>
          </div>
          <div class="view-profile">
            <button type="button">
              View Profile
              <i class="fa-solid fa-arrow-right"></i>
            </button>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="col task-col">
    <div class="task">
      <span class="bar completed"></span>
      <div class="details">
        <div>Completed</div>
        <p>6 tasks</p>
      </div>
      <i class="fa-solid fa-pen edit"></i>
    </div>
    <div class="task">
      <span class="bar active"></span>
      <div class="details">
        <div>Active</div>
        <p>1 task</p>
      </div>
      <i class="fa-solid fa-pen edit"></i>
    </div>
    <div class="task">
      <span class="bar new"></span>
      <div class="details">
        <div>Assigned</div>
        <p>12 tasks</p>
      </div>
      <i class="fa-solid fa-pen edit"></i>
    </div>
    <button type="button">
      <i class="fa-solid fa-plus"></i>Create New Group
    </button>
  </div>
</div>
<br /><br />
<div class="card">
  <div class="card-head">Lorem ipsum - Dashboard</div>
  <div class="card-body">
    What is Lorem Ipsum?<br />
    Lorem Ipsum is simply dummy text of the printing and typesetting industry.
    Lorem Ipsum has been the industry's standard dummy text ever since the
    1500s, when an unknown printer took a galley of type and scrambled it to
    make a type specimen book. It has survived not only five centuries, but also
    the leap into electronic typesetting, remaining essentially unchanged. It
    was popularised in the 1960s with the release of Letraset sheets containing
    Lorem Ipsum passages, and more recently with desktop publishing software
    like Aldus PageMaker including versions of Lorem Ipsum. <br />
    <br />
    Why do we use it?<br />
    It is a long established fact that a reader will be distracted by the
    readable content of a page when looking at its layout. The point of using
    Lorem Ipsum is that it has a more-or-less normal distribution of letters, as
    opposed to using 'Content here, content here', making it look like readable
    English. Many desktop publishing packages and web page editors now use Lorem
    Ipsum as their default model text, and a search for 'lorem ipsum' will
    uncover many web sites still in their infancy. Various versions have evolved
    over the years, sometimes by accident, sometimes on purpose (injected humour
    and the like). <br />
    <br />
    Where does it come from? <br />
    Contrary to popular belief, Lorem Ipsum is not simply random text. It has
    roots in a piece of classical Latin literature from 45 BC, making it over
    2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney
    College in Virginia, looked up one of the more obscure Latin words,
    consectetur, from a Lorem Ipsum passage, and going through the cites of the
    word in classical literature, discovered the undoubtable source. Lorem Ipsum
    comes from sections 1.10.32 and 1.10.33 of "de Finibus Bonorum et Malorum"
    (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a
    treatise on the theory of ethics, very popular during the Renaissance. The
    first line of Lorem Ipsum, "Lorem ipsum dolor sit amet..", comes from a line
    in section 1.10.32. The standard chunk of Lorem Ipsum used since the 1500s
    is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from
    "de Finibus Bonorum et Malorum" by Cicero are also reproduced in their exact
    original form, accompanied by English versions from the 1914 translation by
    H. Rackham.
  </div>
</div>

<br /><br />
<div class="card">
  <div class="card-head">Lorem ipsum - Dashboard</div>
  <div class="card-body">
    What is Lorem Ipsum?<br />
    Lorem Ipsum is simply dummy text of the printing and typesetting industry.
    Lorem Ipsum has been the industry's standard dummy text ever since the
    1500s, when an unknown printer took a galley of type and scrambled it to
    make a type specimen book. It has survived not only five centuries, but also
    the leap into electronic typesetting, remaining essentially unchanged. It
    was popularised in the 1960s with the release of Letraset sheets containing
    Lorem Ipsum passages, and more recently with desktop publishing software
    like Aldus PageMaker including versions of Lorem Ipsum. <br />
    <br />
    Why do we use it?<br />
    It is a long established fact that a reader will be distracted by the
    readable content of a page when looking at its layout. The point of using
    Lorem Ipsum is that it has a more-or-less normal distribution of letters, as
    opposed to using 'Content here, content here', making it look like readable
    English. Many desktop publishing packages and web page editors now use Lorem
    Ipsum as their default model text, and a search for 'lorem ipsum' will
    uncover many web sites still in their infancy. Various versions have evolved
    over the years, sometimes by accident, sometimes on purpose (injected humour
    and the like). <br />
    <br />
    Where does it come from? <br />
    Contrary to popular belief, Lorem Ipsum is not simply random text. It has
    roots in a piece of classical Latin literature from 45 BC, making it over
    2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney
    College in Virginia, looked up one of the more obscure Latin words,
    consectetur, from a Lorem Ipsum passage, and going through the cites of the
    word in classical literature, discovered the undoubtable source. Lorem Ipsum
    comes from sections 1.10.32 and 1.10.33 of "de Finibus Bonorum et Malorum"
    (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a
    treatise on the theory of ethics, very popular during the Renaissance. The
    first line of Lorem Ipsum, "Lorem ipsum dolor sit amet..", comes from a line
    in section 1.10.32. The standard chunk of Lorem Ipsum used since the 1500s
    is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from
    "de Finibus Bonorum et Malorum" by Cicero are also reproduced in their exact
    original form, accompanied by English versions from the 1914 translation by
    H. Rackham.
  </div>
</div>
```
